name: Run and Upload Script

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python fetch_complete_ter.py

    - name: Upload to server
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USER: ${{ secrets.SSH_USER }}
        PASS: ${{ secrets.SSH_PASS }}
      run: |
        sudo apt update
        sudo apt install -y sshpass
        sshpass -p "$PASS" scp -o StrictHostKeyChecking=no ter_of_mf_performance.xlsx $USER@$HOST:/home/gsquare/products/app/amfi/tmp

